version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: opcua_grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Install JSON API datasource plugin
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    # Allow Grafana to reach host services on Windows Docker Desktop via host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
