// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VentilTesterBackend.Data;

#nullable disable

namespace VentilTesterBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VentilTesterBackend.Models.MeasurementSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdentifierNumber")
                        .HasColumnType("integer");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TestRunMessID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestRunMessID");

                    b.ToTable("MeasurementSets");
                });

            modelBuilder.Entity("VentilTesterBackend.Models.ParameterSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParameterSets");
                });

            modelBuilder.Entity("VentilTesterBackend.Models.TestRun", b =>
                {
                    b.Property<int>("MessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessID"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<int>("BlockIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KonfigurationDetailtestId")
                        .HasColumnType("integer");

                    b.Property<int?>("KonfigurationLangzeittestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("VentilkonfigurationId")
                        .HasColumnType("integer");

                    b.HasKey("MessID");

                    b.HasIndex("KonfigurationDetailtestId");

                    b.HasIndex("KonfigurationLangzeittestId");

                    b.HasIndex("VentilkonfigurationId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("VentilTesterBackend.Models.MeasurementSet", b =>
                {
                    b.HasOne("VentilTesterBackend.Models.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunMessID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("VentilTesterBackend.Models.TestRun", b =>
                {
                    b.HasOne("VentilTesterBackend.Models.ParameterSet", "KonfigurationDetailtestParameterSet")
                        .WithMany()
                        .HasForeignKey("KonfigurationDetailtestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VentilTesterBackend.Models.ParameterSet", "KonfigurationLangzeittestParameterSet")
                        .WithMany()
                        .HasForeignKey("KonfigurationLangzeittestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VentilTesterBackend.Models.ParameterSet", "VentilkonfigurationParameterSet")
                        .WithMany()
                        .HasForeignKey("VentilkonfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KonfigurationDetailtestParameterSet");

                    b.Navigation("KonfigurationLangzeittestParameterSet");

                    b.Navigation("VentilkonfigurationParameterSet");
                });
#pragma warning restore 612, 618
        }
    }
}
